//**************************************************************************
//**************************************************************************
//**                                                                      **
//**  Copyright (c) 2015 - 2017 Shanghai Zhaoxin Semiconductor Co., Ltd.  **
//**                                                                      **
//**************************************************************************
//**************************************************************************

#include"DramDebug.h"
#include"Attribute.h"
#include "zxstring.h"


extern INTN
 EFIAPI
 AsiaStrnCmp (
   IN	   CONST CHAR8				 *FirstString,
   IN	   CONST CHAR8				 *SecondString,
   IN	   UINTN					 Length
   );
 /*
 STATIC Attribute_Input D0F0_tbl[]= {
		{CFG,0x00 , L"XXXXXXXX -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{CFG,0x10 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
 };

 */
 STATIC Attribute_Input D0F3_tbl1[]= {
 {MEM,0xE0003000 ,L"XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003010 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003020 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR WWWWWWWW WWWWWWWW WWWWWWWW WWWWWWWW"}, 
 {MEM,0xE0003030 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR XXXXXXXX RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003040 ,L"RRRRRRRR XXXXXXXX XXXXXXXX RRXXXXXX RRXRRXXX XRRRXXXR RRRRRRRR RRR-RRRR AAAAAAAA RRRRAARR RRRXRRRR RRRRRRRR XXXXXXXX XXXXXXXX RRXXXRXX XXXXXXXX"}, 
 {MEM,0xE0003050 ,L"AARAXRAA RRRRAAAR XXXXXXXX RRRXRRRX XXXXXRRX XXXXXXXX XXXXXXXX XXXXXXXX RRRAARRR RRRARARR RRRRRRRR RRRRRRRR RRRAAAAA RRRRRRRR RRRRRRRX RRRRRRRR"}, 
 {MEM,0xE0003060 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRXXRRRR RRRR-RRR RRRRXXRR RRRRRRRR RRRARRRR RAARRARR RRRRRRRR RRRRRRRR RRRRXXXR RRRRXXXR RRRRRXXX RRRRRRRR"}, 
 {MEM,0xE0003070 ,L"AXAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA XXXXXXXX AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003080 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003090 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030A0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030B0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030C0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030D0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030E0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00030F0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003100 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003110 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003120 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003130 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003140 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003150 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR AARRRRRR AAAAAAAA AAAAAAAA AAAAAARR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003160 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003170 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003180 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003190 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AARAAAAA AAAAAARR RRAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00031A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00031B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00031C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AARAAARA ARAARRAA AAAAAAAA AAAAAAAA AAAARRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00031D0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00031E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00031F0 ,L"RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003200 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003210 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003220 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003230 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003240 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003250 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003260 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003270 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 
 };
 STATIC Attribute_Input D0F3_tbl2[]= {
{MEM,0xE0003280 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003290 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032A0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00032F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003300 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003310 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003320 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003330 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003340 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003350 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003360 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003370 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003380 ,L"RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAARRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003390 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAA- AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00033A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00033B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR AAAAAARR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR"}, 
 {MEM,0xE00033C0 ,L"RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAARR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR"}, 
 {MEM,0xE00033D0 ,L"RRRRRRRR AAAAAAAR RRRRRRRR AAAAAARR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAARR"}, 
 {MEM,0xE00033E0 ,L"RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00033F0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003400 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003410 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003420 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003430 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003440 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003450 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003460 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003470 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003480 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003490 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00034A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00034B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00034C0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00034D0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00034E0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE00034F0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 	
 };	

 STATIC Attribute_Input D0F3_tbl3[]= {
 {MEM,0xE0003500 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003510 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003520 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003530 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003540 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003550 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003560 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003570 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003580 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003590 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00035F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003600 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003610 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003620 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003630 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003640 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003650 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003660 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003670 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003680 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003690 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE00036F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003700 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003710 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003720 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003730 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003740 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003750 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003760 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003770 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 

  };

STATIC Attribute_Input D0F3_tbl4[]= {
	{MEM,0xE0003780 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003790 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00037F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003800 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003810 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003820 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003830 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003840 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003850 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003860 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003870 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003880 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003890 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00038F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003900 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003910 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003920 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003930 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003940 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003950 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003960 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003970 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003980 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE0003990 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039A0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039B0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039C0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039D0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039E0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 {MEM,0xE00039F0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
	 


 
};

 
 STATIC Attribute_Input D0F3_tbl5[]= {
 {MEM,0xE0003A00 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A10 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A20 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A30 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A40 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A50 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A60 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A70 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A80 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003A90 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AA0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AB0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AC0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AD0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AE0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003AF0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B00 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003B10 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003B20 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B30 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B40 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B50 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B60 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B70 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B80 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003B90 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003BA0 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003BB0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003BC0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003BD0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003BE0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003BF0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
 {MEM,0xE0003C00 ,L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR AAAARRRR AAAAAAAA RRRRRRRR RRRRRRRR AAAARRRR AAAAAAAA"}, 
 {MEM,0xE0003C10 ,L"RRRRRRRR RRRRRRRR AAAARRRR AAAAAAAA RRRRRRRR RRRRRRRR AAAARRRR AAAAAAAA RRRRRRRR RRRRRRRR AAAAAAAA AAAAAAAA RRRRRRRR RRRRRRRR AAAARRRR AAAAAAAA"}, 
 {MEM,0xE0003C20 ,L"RRRRRRRR RRAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR AAAAAAAR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRAAAA RRRRRRRR AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C30 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C40 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C50 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C60 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C70 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 

  };
 STATIC Attribute_Input D0F3_tbl6[]= {
 {MEM,0xE0003C80 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003C90 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003CA0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003CB0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 {MEM,0xE0003CC0 ,L"AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA					"}, 
	 };











 STATIC Attribute_Input D0F2_tbl[]= {
		{MEM,0xE0002000 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE0002010 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE0002020 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR WWWWWWWW WWWWWWWW WWWWWWWW WWWWWWWW"}, 
		{MEM,0xE0002030 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE0002040 , L"----RR-- -------- RRRRRR-- -----RRR R------- RRRRRRRR R------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- RRRR---- RRRRRRRR"}, 
		{MEM,0xE0002050 , L"-------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR"}, 
		{MEM,0xE0002060 , L"-------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR"}, 
		{MEM,0xE0002070 , L"-------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR"}, 
		{MEM,0xE0002080 , L"-------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR"}, 
		{MEM,0xE0002090 , L"-------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR -------- -------- RRRR---- RRRRRRRR RRR----- RRRRRR-- RRRRR--- RRRRRRRR"}, 
		{MEM,0xE00020A0 , L"-------- -------- -------- -RRRRR-- RRRRRRR- ----RRRR -------- -------- ----RRRR -------- RRRRRRRA RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE00020B0 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE00020C0 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRAAAAA RRRRRRRR"}, 
		{MEM,0xE00020D0 , L"--R--RR- -------- -------- -------- --R--RR- -------- -------- -------- --R--RR- -------- -------- -------- --R--RR- -------- -------- --------"}, 
		{MEM,0xE00020E0 , L"--R--RR- -------- -------- -------- --R--RR- -------- -------- -------- --R--RR- -------- -------- -------- --R--RR- -------- -------- --------"}, 
		{MEM,0xE00020F0 , L"RRRRRRR- RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- -------- -RRRRAAA ARRRRRRR AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA"}, 
 };
 

/*
 STATIC Attribute_Input D0F5_tbl[]= {
		{CFG,0x00 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{CFG,0x10 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
 };
*/

/*
  STATIC Attribute_Input D17F0_tbl[]= {
		 {CFG,0x00 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		 {CFG,0x10 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
  };
 
  */
  
  /*
  STATIC Attribute_Input PMIO_tbl[]= {
		 {IO,0x800 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		 {IO,0x810 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
  };
 */
	/*

 STATIC Attribute_Input XHCI_MMIO_tbl[]= {
		{MEM,0xE0000000 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		{MEM,0xE0000010 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
 };


  STATIC Attribute_Input XHCI_LEVEL2_tbl[]= {
		 {LEVEL2,0x00 , L"-------- -------- -------- -------- RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR -------- -------- -------- -------- AAAAAAAA RRRRRRRR RRRRRRRR RRRRRRRR"}, 
		 {LEVEL2,0x10 , L"RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR RRRRRRRR"},
  };
 */


 CHAR16 *
 EFIAPI
 StrCpy (
   OUT	   CHAR16					 *Destination,
   IN	   CONST CHAR16 			 *Source
   )
 {
   CHAR16							 *ReturnValue;
 
 
   ReturnValue = Destination;
   while (*Source != 0) {
	 *(Destination++) = *(Source++);
   }
   *Destination = 0;
   return ReturnValue;
 }
 
 UINTN
 EFIAPI
 StrLen (
   IN	   CONST CHAR16 			 *String
   )
 {
   UINTN							 Length;
 
   for (Length = 0; *String != L'\0'; String++, Length++) {
	 //
	 // If PcdMaximumUnicodeStringLength is not zero,
	 // length should not more than PcdMaximumUnicodeStringLength
	 }
   return Length;
 }

 void StrReverse(CHAR16 *Str)
 
 {
 UINTN i,j;
 CHAR16 c;
 
	 for(i = 0, j = StrLen(Str) - 1; i < j; ++i, --j) {
 
		 c = *(Str+i);
 
		 *(Str+i) = *(Str+j) ;
 
		 *(Str+j)  = c;
 
	 }
 
 }


 CHAR16 *FindNextChar(CHAR16 *Str,const CHAR16 c)
	 {
		 CHAR16 *s=Str;
		 
		 if(c==WITNOUT_PARAM)  
		 {
			 while(*s==L'\t' || *s==L' ' || *s==L'\n' || *s==L'\r')
			 {
				 s++;	 
				 if(s==0) 
					 return  s;
			 }
		 }
		 else
		 {
			 while(*s!=c)
			 {
				 s++;
				 if(*s==0)
			   
				 return  s;
			   
			 }				  
		 }
		 
		 return s;
	 }

 
 
 BOOLEAN IsValidPort ( UINT16 Address)
  {
  
	
	if (Address >= gPmioStartPort && Address <= gPmioEndPort && gPmioEndPort > gPmioStartPort)
	   {
		 return FALSE; 
	   }
	   else
	   {
		 return TRUE;
	   }   
  }
 
   const UINT8 PciIOReadByte (UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort, UINT32 byRegOffset)
 {
	 UINT32 RegOffset;
	 UINT8 bRtn=0;
	 
	 RegOffset= (byRegOffset/4 )*4;//DW alignment
	 AsiaPciWrite32(PCI_LIB_ADDRESS(bus, dev, fun, PciIndexPort),RegOffset);
	 bRtn=AsiaPciRead8(PCI_LIB_ADDRESS(bus, dev, fun, PciDataPort + (byRegOffset % 4))); 
	 return bRtn;
 }
	const VOID PciIOWriteByte (UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort, UINT32 byRegOffset,UINT8 data8)
 {
	 UINT32 RegOffset;
	 RegOffset= (byRegOffset/4 )*4;//DW alignment
	 AsiaPciWrite32(PCI_LIB_ADDRESS(bus, dev, fun, PciIndexPort),RegOffset);
	 AsiaPciWrite8(PCI_LIB_ADDRESS(bus, dev, fun, PciDataPort + (byRegOffset % 4)),data8);	 
 }
 const UINT8  ReadByte(CYCLE cyc, UINT64 offset, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)
 {
	 UINT8 bRtn=0;
	 
	 switch(cyc)
	 {
		 case CFG: 
					 bRtn=AsiaPciRead8(PCI_LIB_ADDRESS(bus, dev, fun, offset));
					 break;
		 case MEM:				 
					 bRtn=AsiaMemoryRead8(offset);
					 break;
		 case IO:
					 if(!IsValidPort((UINT16)offset)){
						  bRtn = 0;
						 }
					 else{
						 bRtn = (UINT8)AsiaIoRead8((UINT16)offset);
						 }
					 break;

		 case LEVEL2:
		 			 bRtn=PciIOReadByte(bus, dev, fun,PciIndexPort,PciDataPort,(UINT32) offset);
					 break;

		 default:
					 break;
	 }
		return bRtn;
 }
 
 
 const void WriteByte(CYCLE cyc, UINT64 offset, UINT8 b, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)
 {	 
	 
	 switch(cyc)
	 {

		 case CFG: 
					 AsiaPciWrite8(PCI_LIB_ADDRESS(bus, dev, fun, offset),b);
					 break;
		 case MEM:
					 AsiaMemoryWrite8(offset,b);
					 break;
		 case IO:
					 if(IsValidPort((UINT16)offset))
					 AsiaIoWrite8((UINT16)offset, b);
			 
					 break;

		 case LEVEL2:
		 			 PciIOWriteByte(bus, dev, fun,PciIndexPort,PciDataPort,(UINT32) offset,b);
					 break;
		 default:
					 break;
	 }	  
 
 }

const UINT8 Get1Complementb(UINT8 b, UINT8 mask) 
{
	UINT8 bRtn;
	bRtn = b;
	
	bRtn = (UINT8)~bRtn;	
	
	bRtn &= mask;
	
	bRtn |= (b & (~mask));
	
	return bRtn;
}

const UINT16 Get1Complementw(UINT16 w, UINT16 mask) 
{
	UINT16 wRtn;
	wRtn = w;
	
	wRtn = ( UINT16)~wRtn;	
	
	wRtn &= mask;
	
	wRtn |= (w & (~mask));
	
	return wRtn;
}

const UINT32 Get1Complementd(UINT32 d, UINT32 mask) 
{
	UINT32 dRtn ;
	dRtn = d;
	
	dRtn = (UINT32)~dRtn;	
	
	dRtn &= mask;
	
	dRtn |= (d & (~mask));
	
	return dRtn;
}

const void ExamineByteRWm(CYCLE cyc, UINT64 offset, UINT8 mask, UINT8* rtn, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)  
{
	int i;														    
	UINT8 b1, b2, b3;                                                
   
	b3 = b1 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort);                 
	                                                                
	b1 = Get1Complementb(b1, mask);                                 
	                                                                
	WriteByte(cyc, offset, b1, bus, dev, fun,  PciIndexPort,  PciDataPort);                      
	                                                                
	b2 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort);                      
	                                                                
	// handle rtn here
	for(i=0; i<8; i++)                                              
	{                                                               
		rtn[i] = 0;                                                 
		if((((mask>>i)&0x01) == 1) &&                                
			 ((((b3^b2)>>i) & 0x01) == 1 )                          
			)                                                       
		{                                                           
			rtn[i] = 1;                                             
		}
			}
	
	WriteByte(cyc, offset, b3, bus, dev, fun,  PciIndexPort,  PciDataPort);                      
	                                                                
	b3 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort);
	
	for(i=0; i<8; i++)                                              
	{                                                               
		if(((mask>>i)&0x01) == 1)
		{
			if((rtn[i] == 1) && ((((b3^b2)>>i) & 0x01) == 0 ))
			{
				rtn[i] = 0;		
			}	
		}
	
	}
}

void ExamineByteROm(CYCLE cyc, UINT64 offset, UINT8 mask, UINT8* rtn, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)  
{
	int i;
	UINT8 b1,b3;
	UINT8 b2;
	 	
	
	b3 = b1 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort);
	b1 = Get1Complementb(b1, mask);
	
	WriteByte(cyc, offset, b1, bus, dev, fun,  PciIndexPort,  PciDataPort);
	
	b2 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort);
	
	WriteByte(cyc, offset, b3, bus, dev, fun,  PciIndexPort,  PciDataPort);
	
	for(i=0; i<8; i++)
	{
		rtn[i] = 0;
		if((((mask>>i)&0x01) == 1) &&
			 ((((b3^b2)>>i) & 0x01) == 0 )
			)
		{
			rtn[i] = 1;
		}
	
	}
	
		
}

/**
 * NAME
 *  ExamineByteW1Cm
 *
 * DESCRIPTION
 *  Examine whether a signle byte's attribute is write 1 clear with mask.
 *
 * PARAMETERS
 *  IN Cyc: Cycle.
 *  IN Offset: Offset.
 *  IN Mask: Mask.
 *  OUT Rtn: Return Array Containing The Examine Results.
 *  IN Bus: Bus Number.
 *  IN Dev: Device Number.
 *  IN Fun: Function Number.
 *
 * RETURN
 *  None. 	
 */
const void ExamineByteW1Cm(CYCLE cyc, UINT64 offset, UINT8 mask, UINT8* rtn, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)   
{
	int i;
	UINT8 b1;
	
	b1 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort) ;
    
    // handle rtn here
	for(i=0; i<8; i++)                                              
	{                                                               
		rtn[i] = 0;                                                 

		if(((mask>>i)&0x01) == 1)
		{                                                           
			if(((b1>>i)&0x01) == 0)
			{
				rtn[i] = 2;                                             
				//qCount++;
			}
		}
	}
    
    b1 = b1 | mask;
    
    WriteByte(cyc, offset, b1, bus, dev, fun,  PciIndexPort,  PciDataPort) ;	
    
    b1 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort) ;
    
    for(i=0; i<8; i++)                                              
	{                                                               
		if((((mask>>i)&0x01) == 1) &&                                
			 (((b1>>i)&0x01) == 0 )                          
			)                                                       
		{                                                           
			if(rtn[i] == 0)
			{
				rtn[i] = 1;                                             
			}
		}
	}
 }



const void ExamineByteRW1m(CYCLE cyc, UINT64 offset, UINT8 mask, UINT8* rtn, UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort)  
{
	int i;
	UINT8 b1,b2,b3;
	
	b3=b1 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort) ;
    b1 = Get1Complementb(b1, mask);  
	WriteByte(cyc, offset, b1, bus, dev, fun,  PciIndexPort,  PciDataPort) ;     
    b2 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort) ;     

	// handle rtn here
	for(i=0; i<8; i++)                                              
	{                                                               
		rtn[i] = 0;                                                 
		if((((mask>>i)&0x01) == 1) &&                                
			 ((((b3^b2)>>i) & 0x01) == 1 )                          
			)                                                       
		{                                                           
			rtn[i] = 1;                                             
		}
	}
    
 
	WriteByte(cyc, offset, b3, bus, dev, fun,  PciIndexPort,  PciDataPort) ;					 
																 
 	b3 = ReadByte(cyc, offset, bus, dev, fun,  PciIndexPort,  PciDataPort) ;
     
    for(i=0; i<8; i++)                                              
	{                                                               
		if(((mask>>i)&0x01) == 1)
		{
			if((rtn[i] == 1) && ((((b3^b2)>>i) & 0x01) == 1 ))
			{
				//RW1 only can be write once.
				//If the second write success, then fail.
				rtn[i] = 0;		
			}	
		}
	}
 }

void HandleTable(IN EFI_PEI_SERVICES **PeiServices,CYCLE cyc, UINTN offsetwidth,UINTN bus, UINTN dev, UINTN fun,UINTN  PciIndexPort, UINTN PciDataPort,Attribute_Input tbl)  
{
	
	CHAR16              *Str1=NULL;	
	CHAR16               *Str2=NULL;
	CHAR16               *Str3=NULL;
	UINT8 b;
	UINT8 bMask;
	CHAR16                StrTemp;
    UINTN lstNum=0;
    UINTN accw;
    CHAR16  attrlst[40];	// AAAAAAAA or RRRRRRRRRRRRRRRR or WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    UINTN   i,j, k;
	UINT8 *rtn=NULL; 
	CHAR16 logLst[40];
	UINT64 offset;
	UINT64 base;
	EFI_STATUS Status;


	//PEI_DEBUG((PeiServices, EFI_D_ERROR,"HandleTable() "));
    
	offset=tbl.Offset;
	accw=8;	
	lstNum = 16;
	base=0;
	Str2=Str1=tbl.Attr;
	//PEI_DEBUG((PeiServices, EFI_D_ERROR,"tbl.Attr=%s\n ",tbl.Attr));
	// print the first line: this method should be adjusted for different accw.
	for(i=0; i< offsetwidth; i++){
		PEI_DEBUG((PeiServices, EFI_D_ERROR," "));
		}
	PEI_DEBUG((PeiServices, EFI_D_ERROR," "));

			
		
	
		
	{

	switch(offsetwidth){
			case 2:				
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"%02x ",base+offset));
				break;
			case 4:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"%04x ",base+offset));
				break;
			case 8:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"%08x ",base+offset));
				break;
			default:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"offset invalid"));
				break;
				}

		for(i=0; i<lstNum; i++)
        {
        // get the current attribute list.
        
		(*PeiServices)->SetMem(attrlst, sizeof(CHAR16)*40, 0);
		(*PeiServices)->SetMem(logLst, sizeof(CHAR16)*40, 0);
				

			Str3=Str2+accw;
			StrTemp=*Str3;
            *Str3=0;
			StrCpy(attrlst,Str2);
			StrReverse(attrlst);
			*Str3=StrTemp;
			Str2=FindNextChar(Str3,WITNOUT_PARAM);
			
			if(accw==8){
		  		
				if((cyc==IO)&&(!IsValidPort((UINT16) offset))){
								for(j=0; j<8; j++)
							logLst[j] =L'I';
							}
                	
				else{
					Status = (*PeiServices)->AllocatePool(
								  PeiServices,
								 (sizeof(UINT8)*8),
								  &rtn
							  );
					
					(*PeiServices)->SetMem(rtn, sizeof(UINT8)*8, 0);
                for(j=0; j<8; j++)
                {
                    if(logLst[j] == 0)
                    {
                        bMask = 0x00;
                       	
                       	// find mask.
                       	for(k=j; k<8; k++)
                       	{	
                       		if(attrlst[k] == attrlst[j])
                       		{
                       			bMask |= (0x01<<(k));	
                      		}
                        }

					  
                    	// see what kind of attribute.
                    	if(attrlst[j]== RO)
                    	{
							ExamineByteROm(cyc, base+offset, bMask, rtn, bus, dev, fun,  PciIndexPort, PciDataPort); 	
							
                    	}
                    	else if(attrlst[j]== RW)
                    	{
							ExamineByteRWm(cyc, base+offset, bMask, rtn, bus, dev, fun,  PciIndexPort, PciDataPort); 	
							
                    	}
                    	else if(attrlst[j]== W1C)
                    	{
							ExamineByteW1Cm(cyc, base+offset, bMask, rtn, bus, dev, fun,  PciIndexPort, PciDataPort); 
							
                    	}
                    	else if(attrlst[j]== RW1)//dla_add_070620
                    	{
							ExamineByteRW1m(cyc, base+offset, bMask, rtn, bus, dev, fun,  PciIndexPort, PciDataPort); 	
							
                    	}
                    	else if(attrlst[j]== RESERVED)
                    	{
                    		
                    		for(k=j; k<8; k++)
							{
								if( ((bMask>>k) & 0x01) == 1)
									rtn[k] = 5;	
							}     
							       	
                    	}
                    	else if(attrlst[j]== SRESERVED)
                    	{
                    		for(k=j; k<8; k++)
							{
								if( ((bMask>>k) & 0x01) == 1)
									rtn[k] = 6;	
							}     
							       	
                    	}
                    	else if(attrlst[j] == L'0')
                    	{
                    		b = ReadByte(cyc, base+offset, bus, dev, fun,  PciIndexPort, PciDataPort); 
                    		b &= ~bMask;
							WriteByte(cyc, base+offset, b, bus, dev, fun,  PciIndexPort, PciDataPort);      
							
							// handle rtn array for output.
							for(k=j; k<8; k++)
							{
								if( ((bMask>>k) & 0x01) == 1)
									rtn[k] = 3;	
							}               		
                    	}
                    	else if(attrlst[j] == L'1')
                    	{
                    		b = ReadByte(cyc, base+offset, bus, dev, fun,  PciIndexPort, PciDataPort); 
                    		b |= bMask;
							WriteByte(cyc, base+offset, b, bus, dev, fun,  PciIndexPort, PciDataPort);                     		
							
							// handle rtn array for output.
							for(k=j; k<8; k++)
							{
								if( ((bMask>>k) & 0x01) == 1)
									rtn[k] = 4;	
							}               								
                    	}
						

                		// copy rtn to logLst according to mask.
                		for(k=j; k<8; k++)
                		{
                			if(((bMask>>k) & 0x01) == 1)
                			{
								if(rtn[k] == 0)
                					logLst[k] = L'F';
                				else if(rtn[k] == 1)
                					logLst[k] = L'-';
								else if(rtn[k] == 2)
                					logLst[k] = L'?';                					
               					else if(rtn[k] == 3)
                					//logLst[k] = '0';                					
                					logLst[k] = L'-';                					
								else if(rtn[k] == 4)
                					//logLst[k] = '1';                					                					
                					logLst[k] = L'-';                					                					
                				else if(rtn[k] == 5)
                					//logLst[k] = 'X';
                					logLst[k] = L'-';
								else if(rtn[k] == 6)
                					//logLst[k] = 'S';
                					logLst[k] =L'-';                					
								else 
									logLst[k] = L'!';
                			}
                		} 
                	}
             	} 

				StrReverse(logLst);
				
					}

				offset ++;
            }

            
			PEI_DEBUG((PeiServices, EFI_D_ERROR,"%s ",logLst));
		
        }
		PEI_DEBUG((PeiServices, EFI_D_ERROR,"\n"));
		

		}
}




void Attr_Test(IN EFI_PEI_SERVICES **PeiServices,IN UINT8 Attr_Module){
    UINT8 CountToDump;
	UINT8 Index;

  
	  // Set the PMIO start port and end port.
	  gPmioStartPort = 0x800 + 0x14;
	  gPmioEndPort	 = 0x800 + 0x18;

	
		switch(Attr_Module){
			/*case D0F0_CFG:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F0 PCI\n"));
				
				CountToDump=sizeof(D0F0_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,CFG, 2,0,0,0,0,0,D0F0_tbl[Index]);
					}
				break;
			*/
			case D0F3_MMIO1:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl1)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl1[Index]);
					}
				break;
			case D0F3_MMIO2:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl2)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl2[Index]);
					}
				break;
			case D0F3_MMIO3:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl3)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl3[Index]);
					}				
				break;
			case D0F3_MMIO4:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl4)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl4[Index]);
					}				
				break;	
			case D0F3_MMIO5:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl5)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl5[Index]);
					}				
				break;	
			case D0F3_MMIO6:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F3\n"));
				
				CountToDump=sizeof(D0F3_tbl6)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F3_tbl6[Index]);
					}				
				break;		
			
			case D0F2_MMIO:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F2\n"));
				
				CountToDump=sizeof(D0F2_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,D0F2_tbl[Index]);
					}
				break;
			/*
			case D0F5_CFG:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D0F5 PCI\n"));
				
				CountToDump=sizeof(D0F5_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,CFG, 2,0,0,5,0,0,D0F5_tbl[Index]);
					}
				break;
			*/
			/*
			case D17F0_CFG:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"D17F0 PCI\n"));
				
				CountToDump=sizeof(D17F0_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,CFG, 2,0,17,0,0,0,D17F0_tbl[Index]);
					}
				break;

			*/
			/*

			case PMIO_IO:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"PMIO\n"));
				
				CountToDump=sizeof(PMIO_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,IO, 4,0,0,0,0,0,PMIO_tbl[Index]);
					}
				break;
			*/
			
			/*
			case XHCI_MMIO:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"XHCI_MMIO\n"));
				
				CountToDump=sizeof(XHCI_MMIO_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,MEM, 8,0,0,0,0,0,XHCI_MMIO_tbl[Index]);
					}
				break;

			case XHCI_LEVEL2:
				PEI_DEBUG((PeiServices, EFI_D_ERROR,"XHCI_LEVEL2\n"));
				
				CountToDump=sizeof(XHCI_LEVEL2_tbl)/sizeof(Attribute_Input);
				for (Index= 0; Index < CountToDump; Index++){
					HandleTable(PeiServices,LEVEL2, 4,0,18,0,0x68,0x64,XHCI_LEVEL2_tbl[Index]);
					}
				break;
				*/
				
			default:
				break;
			}


}

VOID CmdAttr(
		IN EFI_PEI_SERVICES **PeiServices,		 
#if (PI_SPECIFICATION_VERSION < 0x00010000) 
		IN PEI_PCI_CFG_PPI *pPCIPPI,
#else
		IN EFI_PEI_PCI_CFG2_PPI *pPCIPPI,
#endif
		IN DRAM_ATTRIBUTE *DramAttr,
		int argc, char *argv[])
{

  UINT8 Attr_Module = D0F3_MMIO1;
  PEI_DEBUG((PeiServices, EFI_D_ERROR,"\n\nDLA_CmdAttr()!!!\n\n"));

  
  if(AsiaStrnCmp(argv[1],"d0f31",5) == 0)
  {
	 Attr_Module=D0F3_MMIO1;		
  } 
  else if(AsiaStrnCmp(argv[1],"d0f32",5) == 0)
  {
     Attr_Module=D0F3_MMIO2;
  }
   else if(AsiaStrnCmp(argv[1],"d0f33",5) == 0)
  {
     Attr_Module=D0F3_MMIO3;
  }
    else if(AsiaStrnCmp(argv[1],"d0f34",5) == 0)
  {
     Attr_Module=D0F3_MMIO4;
  }
	 else if(AsiaStrnCmp(argv[1],"d0f35",5) == 0)
  {
     Attr_Module=D0F3_MMIO5;
  }
	  else if(AsiaStrnCmp(argv[1],"d0f36",5) == 0)
  {
     Attr_Module=D0F3_MMIO6;
  }
  else if(AsiaStrnCmp(argv[1],"d0f2",4) == 0)
  {
	 Attr_Module=D0F2_MMIO;	

  }  

  Attr_Test(PeiServices, Attr_Module);

}


